Announcement function after review from dev to master
PasteUs/PasteMeAdmin pull request #28
Opened 2020-02-15 07:16 UTC by 1059438020

2020-02-15 08:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/controller/AnnounceController.java
> +    Response createAnnouncement(@Valid AnnounceRequestDTO ardto) {
这个名字不会报 warning 吗？

2020-02-15 08:02 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/controller/AnnounceController.java
> +    Response createAnnouncement(@Valid AnnounceRequestDTO ardto) {
我 push 的时候把所有 warning 都解决了

2020-02-15 08:14 UTC, LucienShui requested changes

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/dto/AnnounceRequestDTO.java
> +    @NotNull
不是 link 可以为空吗，为什么有个 `@NotNull`

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/enumeration/AnnounceType.java
> +public enum  AnnounceType implements ValueEnum {
`enum` 后面有两个空格。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/enumeration/AnnounceType.java
> +    AnnounceType(int value) { this.value = value; }
不要写在同一行。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/enumeration/AnnounceType.java
> +    public int getValue() { return value; }
不要写在同一行。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/AnnounceManager.java
> +    Response<Integer> countPage(int pageSize);
Manager 里不要用 `Response` 封装。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/AnnounceManager.java
> +    Response<List<AnnounceDO>> getAnnouncement(int page, int pageSize);
Manager 里不要用 `Response` 封装。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +    @Autowired
`@Autowired` 写在括号里。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +    public boolean createAnnouncement(@Valid AnnounceRequestDTO node) {
起个 `node` 是闹哪样。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +            log.error("Create Announcement error=", e);
`=` 两边要有空格。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +            return true;
不 check `mapper` 的操作结果就直接 `return true`，如果删除失败了呢。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +            log.error("updateAnnouncement error=", e);
格式。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +    public boolean updateAnnouncement(Long id, @Valid AnnounceRequestDTO node) {
命名。

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +        log.warn("Announcement list = {}", list);
为什么要用 `warn`，`info` 或 `debug` 不香吗？

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnounceManagerImpl.java
> +        return Response.success(list);
list 会是 null 吗（我也不确定）？

2020-02-15 08:14 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/AnnounceMapper.java
> +    boolean deleteAnnouncement(@Param("id") Long id);
用软删除吧，不要物理删除。

2020-02-15 08:14 UTC, LucienShui commented on src/test/java/cn/pasteme/admin/manager/AdminManagerTests.java
> +            assertTrue(announceManager.getAnnouncement(1, 3).isSuccess());
Orz 只用检查是否成功吗。

2020-02-15 08:17 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/controller/AnnounceController.java
> +    Response createAnnouncement(@Valid AnnounceRequestDTO ardto) {
OK

2020-02-15 08:25 UTC, LucienShui requested changes

2020-02-15 08:25 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/controller/AnnounceController.java
> +    Response deleteAnnouncement(Long id) {
明确一下 `Response` 里包的是什么东西吧（虽然我以前也写过这样的代码）。

2020-02-15 08:25 UTC, LucienShui commented on src/test/java/cn/pasteme/admin/mapper/AdminMapperTests.java
> +import cn.pasteme.admin.enumeration.*;
不要 `import *`

2020-02-15 08:25 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/AnnounceMapper.java
> +public interface AnnounceMapper {
为什么要用动词而不是名词。

2020-02-15 08:25 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/AnnounceMapper.java
> +import org.apache.ibatis.annotations.*;
不要 `import *`

2020-02-15 08:33 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/dto/AnnounceRequestDTO.java
> +    @NotNull
我的错，想当然了

2020-02-16 03:53 UTC, LucienShui requested changes

2020-02-16 03:53 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +        List<AnnounceDO> list = announcementMapper.getAnnouncementByPage((page-1) * pageSize, pageSize);
代码格式，`(page - 1) * pageSize, pageSize`。

2020-02-16 03:53 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +}
有 `Exception` 的话抛出去。

2020-02-16 03:53 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/AnnouncementMapper.java
> +            " WHERE `id`=#{id}"})
`=` 两边空格。

2020-02-16 03:53 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/AnnouncementMapper.java
> +            "WHERE `id`=#{id}" })
`=` 两边空格。

2020-02-16 03:53 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/TableMapper.java
> +            "    `date` TIMESTAMP       NOT NULL COMMENT '创建时间',",
这一行的空格为什么那么多。

2020-02-16 03:53 UTC, LucienShui commented on src/main/resources/sql/init/pasteme_admin_announce.sql
> +    `date` TIMESTAMP       NOT NULL COMMENT '创建时间',
空格太多。

2020-02-16 03:53 UTC, LucienShui commented on src/main/resources/sql/init/pasteme_admin_announce.sql
> +    `link`  VARCHAR(255),
空格太多。

2020-02-16 03:53 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/TableMapper.java
> +            "    `link`  VARCHAR(255),",
空格太多。

2020-02-16 06:00 UTC, LucienShui requested changes

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/entity/AnnounceDO.java
> +    private Date time;
加一个 `创建时间` 的字段。

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/entity/AnnounceDO.java
> +    private AnnounceType type;
没有注释。

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +            log.error("get Announcement, error = ", e);
Exception 要抛出去。

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +            log.error("Announce All error = ", e);
Exception 要抛出去。

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +            log.error("Update Announcement error = ", e);
Exception 要抛出去。

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +            log.error("When delete announcement, error = ", e);
Exception 要抛出去。

2020-02-16 06:00 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> +            log.error("Create Announcement error = ", e);
Exception 要抛出去。

2020-02-16 12:41 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/enumeration/AnnounceType.java
> + *
空行

2020-02-16 12:41 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/manager/AnnouncementManager.java
> + *
空行

2020-02-16 12:41 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/manager/impl/AnnouncementManagerImpl.java
> + *
空行

2020-02-16 12:41 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/mapper/AnnouncementMapper.java
> + *
空行

2020-02-16 12:41 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/mapper/AnnouncementMapper.java
> +    @Update({"UPDATE `pasteme_admin_announce`",
需不需要同时更新修改时间？

2020-02-18 03:07 UTC, LucienShui commented on src/main/java/cn/pasteme/admin/mapper/AnnouncementMapper.java
> +    @Update({"UPDATE `pasteme_admin_announce`",
这个 comment 为什么 ignore 了？

2020-02-18 03:14 UTC, 1059438020 commented on src/main/java/cn/pasteme/admin/mapper/AnnouncementMapper.java
> +    @Update({"UPDATE `pasteme_admin_announce`",
这个地方当时讨论了一下，暂时没有删除时间的需求，暂时没改

2020-02-18 03:21 UTC, LucienShui approved these changes

2020-02-20 03:10 UTC, merged